version: '3'
services:
  uma-db:
    image: "postgres:12"
    ports:
      - "15433:5432"
    environment:
      - POSTGRES_USER=uma-admin
      - POSTGRES_PASSWORD=just-a-pass
      - POSTGRES_DB=uma
    volumes:
      - uma-data:/var/lib/postgresql/data/
volumes:
  uma-data: