spring:
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/uma
    username: uma-admin
    password: just-a-pass

logging:
  level:
    com.introduct.uma: debug
    o.s.web.client.RestTemplate: debug
    root: info
