spring:
  datasource:
    url: jdbc:postgresql://localhost:15433/uma
    username: uma-admin
    password: just-a-pass
  jpa:
    hibernate:
      ddl-auto: none

logging:
  level:
    com.introduct.uma: debug
    o.s.web.client.RestTemplate: debug
    root: info
